//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemRezerwacjiKortow.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemRezerwacjiKortow.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the program.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding court.
        /// </summary>
        public static string AddingCourt {
            get {
                return ResourceManager.GetString("AddingCourt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding gear.
        /// </summary>
        public static string AddingGear {
            get {
                return ResourceManager.GetString("AddingGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding Post.
        /// </summary>
        public static string AddingPost {
            get {
                return ResourceManager.GetString("AddingPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin panel.
        /// </summary>
        public static string AdminPanel {
            get {
                return ResourceManager.GetString("AdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisement name.
        /// </summary>
        public static string AdvertisementName {
            get {
                return ResourceManager.GetString("AdvertisementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisements.
        /// </summary>
        public static string Advertisements {
            get {
                return ResourceManager.GetString("Advertisements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Courts.
        /// </summary>
        public static string AllCourts {
            get {
                return ResourceManager.GetString("AllCourts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Gears.
        /// </summary>
        public static string AllGears {
            get {
                return ResourceManager.GetString("AllGears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available amount.
        /// </summary>
        public static string AmountAvailable {
            get {
                return ResourceManager.GetString("AmountAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of hours.
        /// </summary>
        public static string AmountOfHours {
            get {
                return ResourceManager.GetString("AmountOfHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available gear.
        /// </summary>
        public static string AvailableGear {
            get {
                return ResourceManager.GetString("AvailableGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In case of any questions about specific tennis court, please contact court&apos;s manager first (available at &lt;a href=&quot;#&quot;&gt;Courts&lt;/a&gt; page)..
        /// </summary>
        public static string CallCourtManagerNote {
            get {
                return ResourceManager.GetString("CallCourtManagerNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel reservation.
        /// </summary>
        public static string CancelReservation {
            get {
                return ResourceManager.GetString("CancelReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can reserve.
        /// </summary>
        public static string CanReserve {
            get {
                return ResourceManager.GetString("CanReserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can reserve.
        /// </summary>
        public static string CanReserver {
            get {
                return ResourceManager.GetString("CanReserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change language, head to the Navigation Bar. There you will find Language tab. Click it to choose one from the list..
        /// </summary>
        public static string ChangeLanguageAnswer {
            get {
                return ResourceManager.GetString("ChangeLanguageAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 300 characters remaining.
        /// </summary>
        public static string CharsRemainingContent {
            get {
                return ResourceManager.GetString("CharsRemainingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50 characters remaining.
        /// </summary>
        public static string CharsRemainingTitle {
            get {
                return ResourceManager.GetString("CharsRemainingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check availability to.
        /// </summary>
        public static string CheckAvailability {
            get {
                return ResourceManager.GetString("CheckAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Day.
        /// </summary>
        public static string ChooseDay {
            get {
                return ResourceManager.GetString("ChooseDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -10% from each price.
        /// </summary>
        public static string ClientDiscount {
            get {
                return ResourceManager.GetString("ClientDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Questions.
        /// </summary>
        public static string CommonQuestions {
            get {
                return ResourceManager.GetString("CommonQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex.
        /// </summary>
        public static string Complex {
            get {
                return ResourceManager.GetString("Complex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex data.
        /// </summary>
        public static string ComplexData {
            get {
                return ResourceManager.GetString("ComplexData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex name.
        /// </summary>
        public static string ComplexName {
            get {
                return ResourceManager.GetString("ComplexName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event ID.
        /// </summary>
        public static string ContestID {
            get {
                return ResourceManager.GetString("ContestID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contest name.
        /// </summary>
        public static string ContestName {
            get {
                return ResourceManager.GetString("ContestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contests.
        /// </summary>
        public static string Contests {
            get {
                return ResourceManager.GetString("Contests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Court.
        /// </summary>
        public static string Court {
            get {
                return ResourceManager.GetString("Court", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Court ID.
        /// </summary>
        public static string CourtID {
            get {
                return ResourceManager.GetString("CourtID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indoor tennis court.
        /// </summary>
        public static string CourtIndoor {
            get {
                return ResourceManager.GetString("CourtIndoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Court name.
        /// </summary>
        public static string CourtName {
            get {
                return ResourceManager.GetString("CourtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Court number.
        /// </summary>
        public static string CourtNumber {
            get {
                return ResourceManager.GetString("CourtNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courts.
        /// </summary>
        public static string Courts {
            get {
                return ResourceManager.GetString("Courts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently chosen currency:.
        /// </summary>
        public static string CurrentCurrency {
            get {
                return ResourceManager.GetString("CurrentCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer ID.
        /// </summary>
        public static string CustomerID {
            get {
                return ResourceManager.GetString("CustomerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclic Reservation.
        /// </summary>
        public static string CyclicReservation {
            get {
                return ResourceManager.GetString("CyclicReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclic reservation allows user to reserve court every week at specified hour. Thanks to that user can train at the same hours every week without re-reserving his order. To use cyclic reservation, simply check checkbox when reserving court..
        /// </summary>
        public static string CyclicReservationAnswer {
            get {
                return ResourceManager.GetString("CyclicReservationAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ups! Looks like this date has already been taken :(.
        /// </summary>
        public static string CyclicReservationError {
            get {
                return ResourceManager.GetString("CyclicReservationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a cyclic reservation order.
        /// </summary>
        public static string CyclicReservationForm {
            get {
                return ResourceManager.GetString("CyclicReservationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclic Reservation ID.
        /// </summary>
        public static string CyclicReservationID {
            get {
                return ResourceManager.GetString("CyclicReservationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date cancel reservation.
        /// </summary>
        public static string DateCancel {
            get {
                return ResourceManager.GetString("DateCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date end.
        /// </summary>
        public static string DateEnd {
            get {
                return ResourceManager.GetString("DateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DateInsert {
            get {
                return ResourceManager.GetString("DateInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DateOfInsert {
            get {
                return ResourceManager.GetString("DateOfInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date payment.
        /// </summary>
        public static string DatePayment {
            get {
                return ResourceManager.GetString("DatePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date start.
        /// </summary>
        public static string DateStart {
            get {
                return ResourceManager.GetString("DateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval (how many days).
        /// </summary>
        public static string DayInterval {
            get {
                return ResourceManager.GetString("DayInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of month.
        /// </summary>
        public static string DayOfMonth {
            get {
                return ResourceManager.GetString("DayOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of week.
        /// </summary>
        public static string DayOfWeek {
            get {
                return ResourceManager.GetString("DayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of day of week.
        /// </summary>
        public static string DayOfWeekNumber {
            get {
                return ResourceManager.GetString("DayOfWeekNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string DayWeek1 {
            get {
                return ResourceManager.GetString("DayWeek1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string DayWeek2 {
            get {
                return ResourceManager.GetString("DayWeek2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string DayWeek3 {
            get {
                return ResourceManager.GetString("DayWeek3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string DayWeek4 {
            get {
                return ResourceManager.GetString("DayWeek4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string DayWeek5 {
            get {
                return ResourceManager.GetString("DayWeek5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string DayWeek6 {
            get {
                return ResourceManager.GetString("DayWeek6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string DayWeek7 {
            get {
                return ResourceManager.GetString("DayWeek7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Account.
        /// </summary>
        public static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this.
        /// </summary>
        public static string DeleteQuestion {
            get {
                return ResourceManager.GetString("DeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteTitle {
            get {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content DE.
        /// </summary>
        public static string DescriptionDE {
            get {
                return ResourceManager.GetString("DescriptionDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content EN.
        /// </summary>
        public static string DescriptionEN {
            get {
                return ResourceManager.GetString("DescriptionEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content PL.
        /// </summary>
        public static string DescriptionPL {
            get {
                return ResourceManager.GetString("DescriptionPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of different users.
        /// </summary>
        public static string DifferentUsers {
            get {
                return ResourceManager.GetString("DifferentUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due payment.
        /// </summary>
        public static string DuePayment {
            get {
                return ResourceManager.GetString("DuePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit complex date.
        /// </summary>
        public static string EditComplex {
            get {
                return ResourceManager.GetString("EditComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit opening hours.
        /// </summary>
        public static string EditOpeningHours {
            get {
                return ResourceManager.GetString("EditOpeningHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br/&gt;&lt;br/&gt;Regards, &lt;br/&gt;Your Courts Team.
        /// </summary>
        public static string EmailEnding {
            get {
                return ResourceManager.GetString("EmailEnding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mail address provided is already in the database.
        /// </summary>
        public static string EmailExistsMessage {
            get {
                return ResourceManager.GetString("EmailExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Courts.
        /// </summary>
        public static string EmailFrom {
            get {
                return ResourceManager.GetString("EmailFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string EmailHello {
            get {
                return ResourceManager.GetString("EmailHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been successfully created. &lt;br/&gt; To activate your account, click the activation link below:.
        /// </summary>
        public static string EmailVerificationBody {
            get {
                return ResourceManager.GetString("EmailVerificationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything is almost ready. Activation link to the account was sent to the email: .
        /// </summary>
        public static string EmailVerificationMessage {
            get {
                return ResourceManager.GetString("EmailVerificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been successfully created.
        /// </summary>
        public static string EmailVerificationSubject {
            get {
                return ResourceManager.GetString("EmailVerificationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date field is required.
        /// </summary>
        public static string EnterDate {
            get {
                return ResourceManager.GetString("EnterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description field is required.
        /// </summary>
        public static string EnterDescription {
            get {
                return ResourceManager.GetString("EnterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your e-mail.
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name field is required.
        /// </summary>
        public static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new password.
        /// </summary>
        public static string EnterNewPassword {
            get {
                return ResourceManager.GetString("EnterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter old password.
        /// </summary>
        public static string EnterOldPassword {
            get {
                return ResourceManager.GetString("EnterOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City field is required.
        /// </summary>
        public static string EnterYourCity {
            get {
                return ResourceManager.GetString("EnterYourCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password field is required.
        /// </summary>
        public static string EnterYourConfirmPassword {
            get {
                return ResourceManager.GetString("EnterYourConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth field is required.
        /// </summary>
        public static string EnterYourDateOfBirth {
            get {
                return ResourceManager.GetString("EnterYourDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email field is required.
        /// </summary>
        public static string EnterYourEmail {
            get {
                return ResourceManager.GetString("EnterYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name field is required.
        /// </summary>
        public static string EnterYourName {
            get {
                return ResourceManager.GetString("EnterYourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password field is required.
        /// </summary>
        public static string EnterYourPassword {
            get {
                return ResourceManager.GetString("EnterYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone field is required.
        /// </summary>
        public static string EnterYourPhone {
            get {
                return ResourceManager.GetString("EnterYourPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code field is required.
        /// </summary>
        public static string EnterYourPostalCode {
            get {
                return ResourceManager.GetString("EnterYourPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street field is required.
        /// </summary>
        public static string EnterYourStreet {
            get {
                return ResourceManager.GetString("EnterYourStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname field is required.
        /// </summary>
        public static string EnterYourSurname {
            get {
                return ResourceManager.GetString("EnterYourSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment rental.
        /// </summary>
        public static string EquipmentRental {
            get {
                return ResourceManager.GetString("EquipmentRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of equipment.
        /// </summary>
        public static string EquipmentType {
            get {
                return ResourceManager.GetString("EquipmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must have a minimum of 6 characters.
        /// </summary>
        public static string ErrorPasswordLength {
            get {
                return ResourceManager.GetString("ErrorPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords do not match.
        /// </summary>
        public static string ErrorPasswordMatch {
            get {
                return ResourceManager.GetString("ErrorPasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing the request.
        /// </summary>
        public static string ErrorRequest {
            get {
                return ResourceManager.GetString("ErrorRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event name.
        /// </summary>
        public static string EventName {
            get {
                return ResourceManager.GetString("EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the &lt;strong&gt;F&lt;/strong&gt;requentry &lt;strong&gt;A&lt;/strong&gt;sked &lt;strong&gt;Q&lt;/strong&gt;uestions page! Here is the list containing important and common questions about this website. If you can&apos;t find an answer to your question, please contact with us at Contact page..
        /// </summary>
        public static string FAQIntro {
            get {
                return ResourceManager.GetString("FAQIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Courts.
        /// </summary>
        public static string FreeCourts {
            get {
                return ResourceManager.GetString("FreeCourts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear.
        /// </summary>
        public static string Gear {
            get {
                return ResourceManager.GetString("Gear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear amount.
        /// </summary>
        public static string GearAmount {
            get {
                return ResourceManager.GetString("GearAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear ID.
        /// </summary>
        public static string GearID {
            get {
                return ResourceManager.GetString("GearID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear name.
        /// </summary>
        public static string GearName {
            get {
                return ResourceManager.GetString("GearName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gears.
        /// </summary>
        public static string Gears {
            get {
                return ResourceManager.GetString("Gears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate PDF.
        /// </summary>
        public static string GeneratePDF {
            get {
                return ResourceManager.GetString("GeneratePDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here.
        /// </summary>
        public static string Here {
            get {
                return ResourceManager.GetString("Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CALENDAR.
        /// </summary>
        public static string HomeCalendar {
            get {
                return ResourceManager.GetString("HomeCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT.
        /// </summary>
        public static string HomeContact {
            get {
                return ResourceManager.GetString("HomeContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTESTS.
        /// </summary>
        public static string HomeContests {
            get {
                return ResourceManager.GetString("HomeContests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COURTS.
        /// </summary>
        public static string HomeCourts {
            get {
                return ResourceManager.GetString("HomeCourts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEAR.
        /// </summary>
        public static string HomeGear {
            get {
                return ResourceManager.GetString("HomeGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEWS.
        /// </summary>
        public static string HomeNews {
            get {
                return ResourceManager.GetString("HomeNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRICE LIST.
        /// </summary>
        public static string HomePrice {
            get {
                return ResourceManager.GetString("HomePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to change language?.
        /// </summary>
        public static string HowToChangeLanguage {
            get {
                return ResourceManager.GetString("HowToChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s very easy! First head to navigation bar and select Register tab on the right. You will be redirected to Registration page. Fill form with your credentials and press Register button. You should see a message about successfully created account. Now go to your email and open message from Twoje Korty Tenisowe. There you will find activation link. Click on it to activate your account. After that you have access to more website functionalities!.
        /// </summary>
        public static string HowToRegisterAnswer {
            get {
                return ResourceManager.GetString("HowToRegisterAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to register?.
        /// </summary>
        public static string HowToRegisterQuestion {
            get {
                return ResourceManager.GetString("HowToRegisterQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To reserve court, head to Calendar option at home page. Here choose day when you want to reserve court, then hold your left mouse button, select desired hours and release that button. A message will appear with reservation info. Click Save to make a reservation. Keep in mind that your reservation is not instant as administrator or court manager has to confirm. Pay for your order. When your reservation is accepted, you will get confirmation email..
        /// </summary>
        public static string HowToReserveAnswer {
            get {
                return ResourceManager.GetString("HowToReserveAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to reserve court?.
        /// </summary>
        public static string HowToReserveQuestion {
            get {
                return ResourceManager.GetString("HowToReserveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID transaction.
        /// </summary>
        public static string IdTransaction {
            get {
                return ResourceManager.GetString("IdTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An incorrect password is provided.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request.
        /// </summary>
        public static string InvalidRequest {
            get {
                return ResourceManager.GetString("InvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user with the given email address does not exist.
        /// </summary>
        public static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is accepted.
        /// </summary>
        public static string IsAccepted {
            get {
                return ResourceManager.GetString("IsAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is admin.
        /// </summary>
        public static string IsAdmin {
            get {
                return ResourceManager.GetString("IsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is covered.
        /// </summary>
        public static string IsCovered {
            get {
                return ResourceManager.GetString("IsCovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is email veryfied.
        /// </summary>
        public static string IsEmailVeryfied {
            get {
                return ResourceManager.GetString("IsEmailVeryfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is executed.
        /// </summary>
        public static string IsExecuted {
            get {
                return ResourceManager.GetString("IsExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is for doubles.
        /// </summary>
        public static string IsForDoubles {
            get {
                return ResourceManager.GetString("IsForDoubles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to totay.
        /// </summary>
        public static string JustNow {
            get {
                return ResourceManager.GetString("JustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been successfully logged out.
        /// </summary>
        public static string LogoutSuccessful {
            get {
                return ResourceManager.GetString("LogoutSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum value of the discount is 100 (the given value is in percent).
        /// </summary>
        public static string MaxDiscountValue {
            get {
                return ResourceManager.GetString("MaxDiscountValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon. - Fri..
        /// </summary>
        public static string MondayFriday {
            get {
                return ResourceManager.GetString("MondayFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Months.
        /// </summary>
        public static string MonthList {
            get {
                return ResourceManager.GetString("MonthList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string MonthName {
            get {
                return ResourceManager.GetString("MonthName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Raport.
        /// </summary>
        public static string MonthRaport {
            get {
                return ResourceManager.GetString("MonthRaport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string MonthYear {
            get {
                return ResourceManager.GetString("MonthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My reservations.
        /// </summary>
        public static string MyReservations {
            get {
                return ResourceManager.GetString("MyReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you a new user.
        /// </summary>
        public static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no searched courts for choosen dates.
        /// </summary>
        public static string NoSearchedCourts {
            get {
                return ResourceManager.GetString("NoSearchedCourts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening hours.
        /// </summary>
        public static string OpeningHours {
            get {
                return ResourceManager.GetString("OpeningHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizer.
        /// </summary>
        public static string Organizer {
            get {
                return ResourceManager.GetString("Organizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tennis court system.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel.
        /// </summary>
        public static string Panel {
            get {
                return ResourceManager.GetString("Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments history.
        /// </summary>
        public static string PaymentsHistory {
            get {
                return ResourceManager.GetString("PaymentsHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post ID.
        /// </summary>
        public static string PostID {
            get {
                return ResourceManager.GetString("PostID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        public static string Posts {
            get {
                return ResourceManager.GetString("Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price per hour.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price list.
        /// </summary>
        public static string PriceList {
            get {
                return ResourceManager.GetString("PriceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summer price list.
        /// </summary>
        public static string PriceListSummer {
            get {
                return ResourceManager.GetString("PriceListSummer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winter price list.
        /// </summary>
        public static string PriceListWinter {
            get {
                return ResourceManager.GetString("PriceListWinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price weekend ratio.
        /// </summary>
        public static string PriceWeekendRatio {
            get {
                return ResourceManager.GetString("PriceWeekendRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price winter ratio.
        /// </summary>
        public static string PriceWinterRatio {
            get {
                return ResourceManager.GetString("PriceWinterRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile configuration - general.
        /// </summary>
        public static string ProfileConfigurationGeneral {
            get {
                return ResourceManager.GetString("ProfileConfigurationGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeem.
        /// </summary>
        public static string Redeem {
            get {
                return ResourceManager.GetString("Redeem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterNow {
            get {
                return ResourceManager.GetString("RegisterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reservation must be paid at the cash desk no later than 10 minutes before the beginning of the booking. To cancel a reservation, contact.
        /// </summary>
        public static string Reminder {
            get {
                return ResourceManager.GetString("Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I forgot my password.
        /// </summary>
        public static string RemindPassword {
            get {
                return ResourceManager.GetString("RemindPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password.
        /// </summary>
        public static string RepeatPassword {
            get {
                return ResourceManager.GetString("RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation.
        /// </summary>
        public static string Reservation {
            get {
                return ResourceManager.GetString("Reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation of reservation nr.
        /// </summary>
        public static string ReservationConfirmation {
            get {
                return ResourceManager.GetString("ReservationConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservated item.
        /// </summary>
        public static string ReservationName {
            get {
                return ResourceManager.GetString("ReservationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservations.
        /// </summary>
        public static string Reservations {
            get {
                return ResourceManager.GetString("Reservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation Type.
        /// </summary>
        public static string ReservationType {
            get {
                return ResourceManager.GetString("ReservationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve.
        /// </summary>
        public static string Reserve {
            get {
                return ResourceManager.GetString("Reserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to homepage.
        /// </summary>
        public static string ReturnHome {
            get {
                return ResourceManager.GetString("ReturnHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to list.
        /// </summary>
        public static string ReturnToList {
            get {
                return ResourceManager.GetString("ReturnToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue.
        /// </summary>
        public static string Revenue {
            get {
                return ResourceManager.GetString("Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role ID.
        /// </summary>
        public static string RoleID {
            get {
                return ResourceManager.GetString("RoleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for free courts.
        /// </summary>
        public static string Searcher {
            get {
                return ResourceManager.GetString("Searcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up payments.
        /// </summary>
        public static string SetUpPayments {
            get {
                return ResourceManager.GetString("SetUpPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show my reservations.
        /// </summary>
        public static string ShowMyReservations {
            get {
                return ResourceManager.GetString("ShowMyReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No court.
        /// </summary>
        public static string SqlError001 {
            get {
                return ResourceManager.GetString("SqlError001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summer season 2019.
        /// </summary>
        public static string SummerSeason {
            get {
                return ResourceManager.GetString("SummerSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface type.
        /// </summary>
        public static string SurfaceType {
            get {
                return ResourceManager.GetString("SurfaceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tennis Court System is a website made for all tennis enthusiasts. You can here reserve courts for trainings, additional gear, and even organize a tournament. You can also easily participate in tournaments organized by others. We do hope our website will be helpful!.
        /// </summary>
        public static string TennisCourtSystemAnswer {
            get {
                return ResourceManager.GetString("TennisCourtSystemAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThanksForReservation	Thank you for using the services of the Tennis Club Website. Below we send a summary of your booking transaction..
        /// </summary>
        public static string ThanksForReservation {
            get {
                return ResourceManager.GetString("ThanksForReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time from.
        /// </summary>
        public static string TimeFrom {
            get {
                return ResourceManager.GetString("TimeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to.
        /// </summary>
        public static string TimeTo {
            get {
                return ResourceManager.GetString("TimeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title DE.
        /// </summary>
        public static string TitleDE {
            get {
                return ResourceManager.GetString("TitleDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title EN.
        /// </summary>
        public static string TitleEN {
            get {
                return ResourceManager.GetString("TitleEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title PL.
        /// </summary>
        public static string TitlePL {
            get {
                return ResourceManager.GetString("TitlePL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Gear Count.
        /// </summary>
        public static string TotalGearCount {
            get {
                return ResourceManager.GetString("TotalGearCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Hire Count.
        /// </summary>
        public static string TotalHireCount {
            get {
                return ResourceManager.GetString("TotalHireCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Revenue.
        /// </summary>
        public static string TotalHireRevenue {
            get {
                return ResourceManager.GetString("TotalHireRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Tournaments.
        /// </summary>
        public static string UpcomingTournaments {
            get {
                return ResourceManager.GetString("UpcomingTournaments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s manual.
        /// </summary>
        public static string UserManual {
            get {
                return ResourceManager.GetString("UserManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name and surname.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User profile.
        /// </summary>
        public static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been confirmed. Click here to login.
        /// </summary>
        public static string VerificationSuccessful {
            get {
                return ResourceManager.GetString("VerificationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User veryfication.
        /// </summary>
        public static string VerificationUser {
            get {
                return ResourceManager.GetString("VerificationUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First, verify your email address.
        /// </summary>
        public static string VerifyYourEmail {
            get {
                return ResourceManager.GetString("VerifyYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting Reservations.
        /// </summary>
        public static string WaitingReservations {
            get {
                return ResourceManager.GetString("WaitingReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt to delete an ad has been rejected! The advertisement has already been accepted by the administration..
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekend.
        /// </summary>
        public static string Weekend {
            get {
                return ResourceManager.GetString("Weekend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome in tennis world.
        /// </summary>
        public static string WelcomeInTennis {
            get {
                return ResourceManager.GetString("WelcomeInTennis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is cyclic reservation?.
        /// </summary>
        public static string WhatIsCyclicReservation {
            get {
                return ResourceManager.GetString("WhatIsCyclicReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is Tennis Court System?.
        /// </summary>
        public static string WhatIsTennisCourtSystem {
            get {
                return ResourceManager.GetString("WhatIsTennisCourtSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winter season 2019.
        /// </summary>
        public static string WinterSeason {
            get {
                return ResourceManager.GetString("WinterSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winter Season Beginning.
        /// </summary>
        public static string WinterSeasonBeginning {
            get {
                return ResourceManager.GetString("WinterSeasonBeginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winter Season Ending.
        /// </summary>
        public static string WinterSeasonEnding {
            get {
                return ResourceManager.GetString("WinterSeasonEnding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw.
        /// </summary>
        public static string Withdraw {
            get {
                return ResourceManager.GetString("Withdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday - Friday.
        /// </summary>
        public static string WorkingDays {
            get {
                return ResourceManager.GetString("WorkingDays", resourceCulture);
            }
        }
    }
}
